######################################################################
# Automatically generated by qmake (2.01a) Wed Mar 27 10:25:17 2013
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += . Form include src
INCLUDEPATH += . include

# Input
HEADERS += include/ConfFile.hpp
FORMS += Form/ConfFileGUI.ui
SOURCES += src/ConfFile.cpp src/main.cpp
